routes/web.php
<?php

// Auth Controller
Route::get('/',function(){ return redirect()->route('login'); });

Route::middleware('guest')->group(function(){
  Route::get('/login', 'Auth\AuthController@index')->name('login');
  Route::post('/login', 'Auth\AuthController@login');
});

Route::get('/logout', 'Auth\AuthController@logout')->name('logout');


//Common Tasks
Route::middleware('auth')->group(function(){

  Route::get('/dashboard','CommonController@dashboard')->name('dashboard');
  Route::get('/home',function(){ return redirect()->route('dashboard'); });

  //Profile
  Route::group(['prefix'=>'profile'],function(){
    Route::get('/', 'CommonController@profile')->name('profile');
    Route::patch('/update', 'CommonController@updateProfile');
  });

});

Route::middleware('admin_and_manager')->group(function(){
  Route::get('/staff','StaffController@index')->name('staff.index');
});

Route::middleware('admin_only')->group(function(){
  // Staff
  Route::group(['prefix'=>'staff'],function(){
    Route::post('/','StaffController@store')->name('staff.store');
    Route::get('/create','StaffController@create')->name('staff.create');
    Route::put('/{staff}','StaffController@update')->name('staff.update');
    Route::delete('/{staff}','StaffController@destroy')->name('staff.destroy');
    Route::get('/{staff}/edit','StaffController@edit')->name('staff.edit');
    Route::post('/toggle/{user}', 'StaffController@toggle')->name('staff_toggle');
  });

  // Shop
  Route::group(['prefix'=>'shops'],function(){
    Route::get('/','ShopsController@index')->name('shops');
    Route::post('/','ShopsController@store');
    Route::get('/create','ShopsController@create');
    Route::get('/edit/{shop}','ShopsController@edit');
    Route::patch('/{shop}/update','ShopsController@update');
    Route::get('/assign','ShopsController@assignShop');
    Route::post('/assign','ShopsController@updateAssignShop');
    Route::post('/toggle/{shop}', 'ShopsController@toggle')->name('shop_toggle');
  });

  //Roles & Permission
  Route::group(['prefix'=>'roles'],function(){
    Route::get('/', 'RoleController@index')->name('roles');
    Route::get('/create', 'RoleController@create');
    Route::post('/', 'RoleController@store');
    Route::get('/edit/{role}', 'RoleController@edit');
    Route::patch('/{role}/update', 'RoleController@update');
    Route::get('/grant', 'RoleController@showRoles');
    Route::post('/grant/{user}', 'RoleController@grantRoles');
    Route::post('/toggle/{role}', 'RoleController@toggle')->name('role_toggle');
  });

  //Positions
  Route::group(['prefix'=>'positions'],function(){
    Route::get('/', 'PositionController@index')->name('positions');
    Route::get('/create', 'PositionController@create');
    Route::post('/', 'PositionController@store');
    Route::get('/edit/{position}', 'PositionController@edit');
    Route::patch('/{position}/update', 'PositionController@update');
    Route::get('/assign','PositionController@assignPosition');
    Route::post('/assign','PositionController@updatePosition');
    Route::post('/toggle/{position}', 'PositionController@toggle')->name('position_toggle');
  });

  //Payment Methods
  //Route::resource('/payment_methods','PaymentMethodController');

  Route::group(['prefix'=>'payment_methods'],function(){
    Route::get('/', 'PaymentMethodController@index')->name('payment_methods.index');
    Route::post('/', 'PaymentMethodController@store')->name('payment_methods.store');
    Route::get('/create', 'PaymentMethodController@create')->name('payment_methods.create');

    Route::get('/assign', 'PaymentMethodController@showAssign')->name('payment_methods.showAssign');
    Route::post('/assign', 'PaymentMethodController@assign')->name('payment_methods.assign');
    Route::patch('/{payment_method}', 'PaymentMethodController@update')->name('payment_methods.update');
    Route::patch('/{payment_method}/edit', 'PaymentMethodController@edit')->name('payment_methods.edit');
    Route::delete('/{payment_method}', 'PaymentMethodController@destroy')->name('payment_methods.destroy');
    Route::post('/toggle/{payment_method}', 'PaymentMethodController@toggle')->name('payment_method_toggle');
  });

});

//Timesheet
Route::group(['prefix'=>'timesheets'],function(){
  Route::get('/', 'TimesheetController@index')->name('timesheets');
  Route::get('/create', 'TimesheetController@create');
  Route::post('/create', 'TimesheetController@store');
  Route::get('/edit/{timesheet}', 'TimesheetController@edit');
  Route::patch('/create/{timesheet}', 'TimesheetController@update');
  Route::post('/find/staff/{shop}', 'TimesheetController@findStaff');
  Route::post('/record/{record}', 'TimesheetController@findRecord');
  Route::get('/record/{record}', 'TimesheetController@findRecord');
  Route::post('/delete/record/{record}', 'TimesheetController@destroyRecord');
  Route::post('/find/positions/{user}', 'TimesheetController@findPosition');
});

//Assessments
Route::group(['prefix'=>'assessments'],function(){
  Route::get('/', 'AssessmentController@index')->name('assessments');
  Route::get('/create', 'AssessmentController@create');
  Route::post('/create', 'AssessmentController@store');
  Route::get('/assign', 'AssessmentController@assignAssessment');
  Route::post('/assign', 'AssessmentController@updateAssignment');

  Route::get('/edit/{assessment}', 'AssessmentController@edit');
  Route::patch('/edit/{assessment}', 'AssessmentController@update');
  Route::get('/resultlist', 'AssessmentController@resultList');
  Route::post('/toggle/{assessment}', 'AssessmentController@toggle')->name('assessment_toggle');
  Route::get('/result/{user}/{assessment}', 'AssessmentController@getResult');
  Route::post('/result/change', 'AssessmentController@toggleAnswer')->name('change_answer');

  //for staff
  Route::get('/take', 'UserController@getAssessments');
  Route::get('/take/{assessment}', 'UserController@takeAssessment');
  Route::post('/take/{assessment}', 'UserController@submitAssessment');

});
Route::group(['prefix'=>'payment_methods'],function(){
  Route::post('/find/shop/{shop}', 'PaymentMethodController@getPaymentMethods')->name('payment_methods.find');
});

Route::group(['prefix'=>'eod'],function(){
  Route::resource('/sale','SaleController');
});

app/Sale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    //
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SaleController extends Controller
{
    public function index()
    {
    	return view('staff.sale.index');
    }
    public function create()
    {
      try {
        return view('staff.sale.create',[
          'shops'=>auth()->user()->shops
        ]);
      } catch (\Exception $e) {
        \Log::info(['SaleController@index'=>$e]);
        return redirect('404');
      }


    }
    public function store(Request $request)
    {
      dd($request->all());
    }
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Staff\CreateRequest;
use App\Http\Requests\Staff\EditRequest;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use App\User;
use App\Shop;

class StaffController extends CommonController
{
    public function __construct(){
      parent::__construct();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user){

      try {
        if(auth()->user()->hasRole('Manager')){
          return view('manager.staff.list',['users'=>auth()->user()->getUsersFromShop()]);
        }
        return view('admin.staff.list',['users'=>$user->all()]);
      }catch(Exception $e){
        echo $e->getMessage();
      }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      try {
        return view('admin.staff.create',[
          'shoplist'=>Shop::all(),
          'mbittype'=>$this->getMbitType(),
          'rolelists'=>Role::where('status',1)->get(),
        ]);
      }catch(Exception $e){
        echo $e->getMessage();
      }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      try {
        $this->validate($request,[
          'email'=>'required|email|max:191|unique:users',
          'firstname'=>'required|alpha|max:30',
          'lastname'=>'required|alpha|max:30',
          'username'=>'required|max:25|unique:users',
          'password'=>'required|max:25',
          'origin_country'=>'alpha|nullable|max:30',
          'dedicated_shop'=>'required',
        ]);

        $user=new User();
        $user->fill($request->all());
        $user->password=$request->password;
        $user->save();
        $user->Shops()->sync(request('shop_ids'));
        $user->Roles()->sync(request('role_id'));
        return redirect()->route('staff.index')->with('message','Staff has been created successfully..!');
      }catch(Exception $e){
        echo $e->getMessage();
      }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $staff)
    {

      try {
        return view('admin.staff.edit',[
          'shoplist'=>Shop::all(),
          'mbittype'=>$this->getMbitType(),
          'rolelists'=>Role::where('status',1)->get(),
          'user'=>$staff,
          'additional'=>($staff->shops->pluck('id')->all()==null)?[]:$staff->shops->pluck('id')->all(),
        ]);
      } catch (Exception $e) {
        echo $e->getMessage();
      }
    }

    /**
     * Update the specified resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(EditRequest $req,User $staff){

      $staff->update(request()->all());
      if(request('password')!='' && !\Hash::check(request('password'),$staff->password)){
        $staff->password=request('password');
        $staff->save();
      }
      if(request('role_id')!==null)
        $staff->Roles()->sync(request('role_id'));

      $staff->Shops()->sync([
        request('dedicated_shop')=>['is_dedicated'=>'1'],
      ]);
      $staff->Shops()->syncWithoutDetaching(request('shop_ids'));
      
      return redirect()
        ->route('staff.index')
        ->with('message','User has been updated successfully..!');
    }

    /**
     * Toggle the specified resource in storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function toggle(User $user)
    {
      try {
        $user->update([
          'status'=>(!$user->status)
        ]);
        return \Response::json([
          'resultCode'=>'success',
          'status'=>$user->status
        ]);
      } catch (\Exception $e) {
        \Log::error('error',[$e->getMessage()]);
      }
    }
}

resources/views/staff/sale/create.blade.php
@extends('master')
@section('title','Create EOD')
@section('pagename','Add EOD')
@section('headerscript')
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="/plugins/iCheck/all.css">
<style media="screen">
  .table-condensed > tbody > tr > td{padding:2px;}
  .box-header{padding:7px;}
  .box{margin-bottom:10px;}
  .form-group{margin-bottom:4px;}
</style>
@endsection
@section('contents')
<section class="content-header">
  <h1>@yield('pagename')</h1>

</section>
<!-- Main content -->
<section class="content">

  @include('pages.partials.errors')
  @include('pages.partials.success')

  <form role="form" action='{{route('sale.store')}}' method='post'>
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title">Sale Summary</h3>
                <span class='pull-right'><u><strong>@{{date}} - @{{day}}</strong></u></span>
              </div>
              <div class="box-body">
                <div class="form-group">
                  <input type="text" name="date" class="form-control" value="{{Date('Y-m-d')}}" disabled/>
                </div>
                <div class="form-group">
                  <label>Shop</label>
                  <select required v-on:change="getPaymentMethods()" v-model="shop" name="shop" class="form-control">
                    <option selected value="">Select Shop</option>
                    @foreach ($shops as $shop)
                      <option value="{{$shop->id}}">{{$shop->name}}</option>
                    @endforeach
                  </select>
                </div>
                <div class="form-group">
                  <input required name="opening_float" placeholder="Opening Float" class="form-control" />
                </div>

                <div class="form-group" v-for="payment_method in payment_methods">
                  <input required v-model.number="payment_method.value" :name="'payment_methods['+`${payment_method.id}`+'][]'" :placeholder="payment_method.name" class="form-control" />
                </div>

                <div class="form-group">
                  <label>Total Sales</label>
                  <input required v-model.number="total_sales" name="total_sales" placeholder="Total Sales" class="form-control" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title">Cash Payments /Disbursements from Till</h3>
              </div>
              <div class="box-body">
                <table class="table table-condensed table-striped">
                </table>
                <button type='button' v-on:click='calculateTotal()' class="btn btn-success btn-md submit">Add Sale</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title">Actual Cash Count</h3>
              </div>
              <div class="box-body">
                <table class="table table-condensed table-striped">
                  <tr>
                    <th>Unit</th>
                    <th>Qty</th>
                    <th>Amount</th>
                  </tr>
                  <tr v-for='cash in cashCount'>
                    <td>@{{cash.unit}}</td>
                    <td><input :name="'cash_count['+`${cash.unit}`+'][]'" placeholder="0.00" v-model="cash.qty"></td>
                    <td>@{{isNaN(cash.qty)?'0.00':(cash.unit * cash.qty).toFixed(2)}}
                      <input type="hidden" v-model="cash.total" value="isNaN(cash.qty)?0:(cash.unit * cash.qty).toFixed(2)">
                    </td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="box box-info">
              <div class="box-body">
                <div class="form-group">
                  <label>Discount</label>
                  <input type="text" name="discount" class="form-control" value="0.00" />
                </div>
                <div class="form-group">
                  <label>Balance</label>
                  <input type="text" name="balance" class="form-control" value="0.00" />
                </div>
                <div class="form-group">
                  <textarea name="remarks" class="form-control" placeholder="Enter Remarks (Optional)"></textarea>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {{csrf_field()}}
  </form>
</section>
@endsection
@section('footerscript')
<script src="/plugins/iCheck/icheck.min.js"></script>
<script type="text/javascript">
$('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
  checkboxClass: 'icheckbox_minimal-blue',
  radioClass: 'iradio_minimal-blue'
});

var app=new Vue({
  el:'#app',
  data:{
    date:"{{Date('M d, Y')}}",
    day:"{{ucfirst(Date('l'))}}",
    payment_methods:[],
    shop:"",
    total_sales:0,
    cashCount:[{unit:0.1},{unit:0.2},{unit:0.5},{unit:1},{unit:2},
      {unit:5},{unit:10},{unit:20},{unit:50},{unit:100}],
    cash:[]
  },
  methods:{

    getPaymentMethods:function(){
      var Vue=this;
      swal({title: 'Please wait...',showConfirmButton: false});
      $.ajax({
				headers: {'X-CSRF-TOKEN': $('input[name="_token"]').val()},
				url:'/payment_methods/find/shop/'+Vue.shop,
				method: 'post',
				success:function(data){
          swal.close();
					if(data.resultCode=='error'){
            Vue.payment_methods=[];
						sweetAlert("Oops...", data.resultValue, "error");
            Vue.shop="";
					}else if(data.resultCode=='success'){
						Vue.payment_methods=data.resultValue;
					}
				},error:function(data){
					sweetAlert("Oops...", "Error occured, Please try later..!", "error");
				}
			});
    },
    calculateTotal:function(){
      console.info(this.cashCount);
    }
  },
  computed:{
    totalPayment:function(){
      var tmp=0;
      for(var i=0;i<this.payment_methods.length;i++){
        if(isNaN(this.payment_methods[i].value))
          continue;
        tmp+=this.payment_methods[i].value;
      }
      return tmp;
    },
    // total:function(){
    //   for(var i=0;i<this.cashCount.length;i++){
    //     if(isNaN(this.cashCount[i].qty))
    //       continue;
    //     this.cashCount[i].total=this.cashCount[i].qty*this.cashCount[i].unit;
    //   }
    //
    // }
  }
});
</script>
@endsection

resources/views/staff/sale/edit.blade.php
@extends('master')
@section('title','Edit Shop')
@section('pagename','Shop Information')
@section('contents')
<section class="content-header">
  <h1>@yield('pagename')</h1>
</section>
<!-- Main content -->
<section class="content">
    @include('pages.partials.errors')
  <form role="form" action='/shops/{{$shop->id}}/update' method='post'>
    <div class="row">
      <div class="col-md-12">
        <div class="box box-success">
          <div class="box-body">
            <div class="form-group">
              <label>Shop Name</label>
              <div class="input-group">
                <div class="input-group-addon"><i class="ion ion-beer"></i></div>
                <input id="name" required name="name" placeholder='Enter Shop Name' class="form-control" value="{{$shop->name}}" type="text">
              </div>
            </div>
            <div class="form-group">
              <label>Shop Status : </label>&nbsp;
              <label>
                <input type="radio" {{($shop->status=='1')?'checked':''}} required name="status" value='1' class="minimal"> Active
              </label>
              <label>
                <input type="radio" {{($shop->status=='0')?'checked':''}} required name="status" class="minimal" value='0'> Inactive
              </label>
            </div>
            <button type='submit' name="btnUpdate" class="btn btn-success btn-md submit" id="btnUpdate">Update Shop</button>
          </div>
        </div>
      </div>
    </div>
    {{ csrf_field() }}
    {{ method_field('PATCH') }}
  </form>
</section>
@endsection

resources/views/staff/sale/list.blade.php
@extends('master')
@section('title','Shop List')
@section('pagename','Shops')
@section('contents')
<section class="content-header">
  <h1>@yield('pagename')</h1>
</section>
<!-- Main content -->
<section class="content">
<div class="row">
  <div class="col-xs-12">
    @include('pages.partials.success')
    <div class="box box-primary">
      <div class="box-header">
        <!-- <h3 class="box-title">Hover Data Table</h3> -->
        <a href='/shops/create' class='btn btn-primary'><i class="fa fa-plus"></i> Add More</a>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <!-- @if(isset($status))
          <div class="alert alert-success">
            {{$status}}
          </div>
        @endif -->
        <table id="shopslist" class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>Shop Name</th>
              <th>Status</th>
              <th>Creation Date</th>
              <th class='text-center'>Action</th>
            </tr>
          </thead>
          <tbody>
            @if($shops->count()==0)
              <tr><td colspan='5' align='center'><h4>Records not Found</h4></td></tr>
            @else
              @foreach ($shops as $shop)
                <tr>
                  <td>{{$shop->name}}</td>
                  <td>
                    <a href='{{route('shop_toggle',$shop->id)}}' class='toggleStatus' title='click to toggle'>
                      <span class="label bg-{{($shop->status=='1')?'green':'red'}}">
                        {{($shop->status=='1')?'Active':'Inactive'}}
                      </span>
                    </a>
                  </td>
                  <td>{{$shop->created_at->toDateString()}}</td>
                  <td align='center'><a title='Edit' class='purple' href="shops/edit/{{$shop->id}}"><i class='fa fa-pencil'></i></a></td>
                </tr>
              @endforeach
            @endif
          </tbody>
        </table>
        {{csrf_field()}}
      </div>
      <!-- /.box-body -->
    </div>
  </div>
</div>
</section>
@endsection
@section('script')
<script type="text/javascript">
$(document).ready(function(){
  $('.status_confirm').click(function(e){
    if(!confirm('Are you sure you want to change the user\'s status ?')){
      e.preventDefault();
      return false;
    }
  });
});
</script>
@endsection