routes/web.php
<?php

// Auth Controller
Route::get('/',function(){ return redirect()->route('login'); });

Route::middleware('guest')->group(function(){
  Route::get('/login', 'Auth\AuthController@index')->name('login');
  Route::post('/login', 'Auth\AuthController@login');
});

Route::get('/logout', 'Auth\AuthController@logout')->name('logout');


//Common Tasks
Route::middleware('auth')->group(function(){

  Route::get('/dashboard','CommonController@dashboard')->name('dashboard');
  Route::get('/home',function(){ return redirect()->route('dashboard'); });

  //Profile
  Route::group(['prefix'=>'profile'],function(){
    Route::get('/', 'CommonController@profile')->name('profile');
    Route::patch('/update', 'CommonController@updateProfile');
  });

});

Route::middleware('admin_and_manager')->group(function(){
  Route::get('/staff','StaffController@index')->name('staff.index');
});

Route::middleware('admin_only')->group(function(){
  // Staff
  Route::group(['prefix'=>'staff'],function(){
    Route::post('/','StaffController@store')->name('staff.store');
    Route::get('/create','StaffController@create')->name('staff.create');
    Route::put('/{staff}','StaffController@update')->name('staff.update');
    Route::delete('/{staff}','StaffController@destroy')->name('staff.destroy');
    Route::get('/{staff}/edit','StaffController@edit')->name('staff.edit');
    Route::post('/toggle/{user}', 'StaffController@toggle')->name('staff_toggle');
  });

  // Shop
  Route::group(['prefix'=>'shops'],function(){
    Route::get('/','ShopsController@index')->name('shops');
    Route::post('/','ShopsController@store');
    Route::get('/create','ShopsController@create');
    Route::get('/edit/{shop}','ShopsController@edit');
    Route::patch('/{shop}/update','ShopsController@update');
    Route::get('/assign','ShopsController@assignShop');
    Route::post('/assign','ShopsController@updateAssignShop');
    Route::post('/toggle/{shop}', 'ShopsController@toggle')->name('shop_toggle');
  });

  //Roles & Permission
  Route::group(['prefix'=>'roles'],function(){
    Route::get('/', 'RoleController@index')->name('roles');
    Route::get('/create', 'RoleController@create');
    Route::post('/', 'RoleController@store');
    Route::get('/edit/{role}', 'RoleController@edit');
    Route::patch('/{role}/update', 'RoleController@update');
    Route::get('/grant', 'RoleController@showRoles');
    Route::post('/grant/{user}', 'RoleController@grantRoles');
    Route::post('/toggle/{role}', 'RoleController@toggle')->name('role_toggle');
  });

  //Positions
  Route::group(['prefix'=>'positions'],function(){
    Route::get('/', 'PositionController@index')->name('positions');
    Route::get('/create', 'PositionController@create');
    Route::post('/', 'PositionController@store');
    Route::get('/edit/{position}', 'PositionController@edit');
    Route::patch('/{position}/update', 'PositionController@update');
    Route::get('/assign','PositionController@assignPosition');
    Route::post('/assign','PositionController@updatePosition');
    Route::post('/toggle/{position}', 'PositionController@toggle')->name('position_toggle');
  });

  //Payment Methods
  //Route::resource('/payment_methods','PaymentMethodController');

  Route::group(['prefix'=>'payment_methods'],function(){
    Route::get('/', 'PaymentMethodController@index')->name('payment_methods.index');
    Route::post('/', 'PaymentMethodController@store')->name('payment_methods.store');
    Route::get('/create', 'PaymentMethodController@create')->name('payment_methods.create');

    Route::get('/assign', 'PaymentMethodController@showAssign')->name('payment_methods.showAssign');
    Route::post('/assign', 'PaymentMethodController@assign')->name('payment_methods.assign');
    Route::patch('/{payment_method}', 'PaymentMethodController@update')->name('payment_methods.update');
    Route::patch('/{payment_method}/edit', 'PaymentMethodController@edit')->name('payment_methods.edit');
    Route::delete('/{payment_method}', 'PaymentMethodController@destroy')->name('payment_methods.destroy');
    Route::post('/toggle/{payment_method}', 'PaymentMethodController@toggle')->name('payment_method_toggle');
  });

});

//Timesheet
Route::group(['prefix'=>'timesheets'],function(){
  Route::get('/', 'TimesheetController@index')->name('timesheets');
  Route::get('/create', 'TimesheetController@create');
  Route::post('/create', 'TimesheetController@store');
  Route::get('/edit/{timesheet}', 'TimesheetController@edit');
  Route::patch('/create/{timesheet}', 'TimesheetController@update');
  Route::post('/find/staff/{shop}', 'TimesheetController@findStaff');
  Route::post('/record/{record}', 'TimesheetController@findRecord');
  Route::get('/record/{record}', 'TimesheetController@findRecord');
  Route::post('/delete/record/{record}', 'TimesheetController@destroyRecord');
  Route::post('/find/positions/{user}', 'TimesheetController@findPosition');
});

//Assessments
Route::group(['prefix'=>'assessments'],function(){
  Route::get('/', 'AssessmentController@index')->name('assessments');
  Route::get('/create', 'AssessmentController@create');
  Route::post('/create', 'AssessmentController@store');
  Route::get('/assign', 'AssessmentController@assignAssessment');
  Route::post('/assign', 'AssessmentController@updateAssignment');

  Route::get('/edit/{assessment}', 'AssessmentController@edit');
  Route::patch('/edit/{assessment}', 'AssessmentController@update');
  Route::get('/resultlist', 'AssessmentController@resultList');
  Route::post('/toggle/{assessment}', 'AssessmentController@toggle')->name('assessment_toggle');
  Route::get('/result/{user}/{assessment}', 'AssessmentController@getResult');
  Route::post('/result/change', 'AssessmentController@toggleAnswer')->name('change_answer');

  //for staff
  Route::get('/take', 'UserController@getAssessments');
  Route::get('/take/{assessment}', 'UserController@takeAssessment');
  Route::post('/take/{assessment}', 'UserController@submitAssessment');

});
Route::group(['prefix'=>'payment_methods'],function(){
  Route::post('/find/shop/{shop}', 'PaymentMethodController@getPaymentMethods')->name('payment_methods.find');
});

Route::group(['prefix'=>'eod'],function(){
  Route::resource('/sale','SaleController');
});

resources/views/pages/partials/errors.blade.php
@if (count($errors))
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i> Alert!</h4>
    <ul class='list-unstyled'>
      {!! implode('', $errors->all('<li>:message</li>')) !!}
    </ul>
  </div>
@endif

resources/views/pages/partials/footer.blade.php
<footer class="main-footer">
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6">
      <span>&copy; Copyright  {{ date('Y') }} - <strong>Hulucat </strong></span>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-6">
      <span title='Parth Jani' class='pull-right'><strong><u>Handcrafted by <a href="http://parthjani.in">Parth Jani</a></u></strong></span>
    </div>
  </div>
</footer>

resources/views/pages/partials/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="/dashboard" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>H</b>Cat</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>HULUCAT</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="/dashboard" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">

      <ul class="nav navbar-nav">
        @if(Auth::user())
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/dist/img/avatar5.png" class="user-image" alt="User Image">
              <span class="hidden-xs">{{\Auth::user()->username}}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/dist/img/avatar5.png" class="img-circle" alt="User Image">
                <p>
                  <u>{{\Auth::user()->fullname}}</u>
                  <small><strong>{{\Auth::user()->Roles->first()->name}}</strong></small>
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a href="/profile" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="/logout" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        @endif
      </ul>
    </div>
  </nav>
</header>

resources/views/pages/partials/result.blade.php
<div class="modal result">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title">Assessment Result - <span class='user'></span></h4>
      </div>
      <div class="modal-body" style='padding: 5px 15px;'>
        <div id="question_set">

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

resources/views/pages/partials/sidebar.blade.php
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">NAVIGATION PANEL</li>
      <li>
        <a href="/dashboard"><i class="fa fa-dashboard"></i>&nbsp;<span>Dashboard</span></a>
      </li>
      @hasanyrole('Administrator|Manager')
      <li class="treeview">
        <a href="#">
          <i class="ion ion-person-stalker"></i>
          <span>Staff</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/staff"><i class="fa fa-circle-o"></i> Staff List</a></li>
          <li><a href="/staff/create"><i class="fa fa-circle-o"></i> Add Staff</a></li>
        </ul>
      </li>
      @endhasanyrole
      @hasanyrole('Administrator')
      <li class="treeview">
        <a href="#">
          <i class="fa fa-home"></i>
          <span>Shops</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/shops"><i class="fa fa-circle-o"></i> Shop List</a></li>
          <li><a href="/shops/create"><i class="fa fa-circle-o"></i> Add Shops</a></li>
          <li><a href="/shops/assign"><i class="fa fa-circle-o"></i> Assign Shops</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-briefcase"></i>
          <span>Positions</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/positions"><i class="fa fa-circle-o"></i> Position List</a></li>
          <li><a href="/positions/create"><i class="fa fa-circle-o"></i> Add Position</a></li>
          <li><a href="/positions/assign"><i class="fa fa-circle-o"></i> Assign Position</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-credit-card"></i>
          <span>&nbsp;Payment Methods</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{route('payment_methods.index')}}"><i class="fa fa-circle-o"></i> List</a></li>
          <li><a href="{{route('payment_methods.create')}}"><i class="fa fa-circle-o"></i> Create</a></li>
          <li><a href="{{route('payment_methods.showAssign')}}"><i class="fa fa-circle-o"></i> Assign</a></li>
          <!-- <li><a href="/positions/assign"><i class="fa fa-circle-o"></i> Assign Position</a></li> -->
        </ul>
      </li>
      @endhasanyrole
      @hasanyrole('Manager|Administrator')
      <li class="treeview">
        <a href="#">
          <i class="fa fa-calendar"></i>
          <span>Timesheet</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/timesheets"><i class="fa fa-circle-o"></i> View Timesheet</a></li>
          <li><a href="/timesheets/create"><i class="fa fa-circle-o"></i>Create Timesheet</a></li>
        </ul>
      </li>
      @endhasanyrole
      @hasrole('Administrator')
      <li class="header">Advanced Settings</li>
      <!-- <li class="treeview">
        <a href="#">
          <i class="fa fa-bar-chart"></i>
          <span>User Assessment</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/assessments"><i class="fa fa-circle-o"></i> List Assessments</a></li>
          <li><a href="/assessments/create"><i class="fa fa-circle-o"></i> Create Assessment</a></li>
          <li><a href="/assessments/assign"><i class="fa fa-circle-o"></i> Assign Assessment</a></li>
          <li><a href="/assessments/resultlist"><i class="fa fa-circle-o"></i> Results</a></li>
        </ul>
      </li> -->
      <li class="treeview">
        <a href="#">
          <i class="fa fa-shield"></i>
          <span>Roles & Permissions</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/roles"><i class="fa fa-circle-o"></i> Roles</a></li>
          <!-- <li><a href="/roles/create"><i class="fa fa-circle-o"></i>Add Permission</a></li> -->
          <li><a href="/roles/grant"><i class="fa fa-circle-o"></i> Grant Roles</a></li>
        </ul>
      </li>
      @endhasrole

      @hasanyrole('Manager|Staff')
      <!-- <li class="treeview">
        <a href="#">
          <i class="fa fa-bar-chart"></i>
          <span>Assessments</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="/assessments/take"><i class="fa fa-circle-o"></i> Take Assessments</a></li>
          <li><a href="/assessments/taken"><i class="fa fa-circle-o"></i> Results</a></li>
        </ul>
      </li> -->
      @endhasanyrole
      @hasrole('Staff')
      <li class="treeview">
        <a href="#">
          <i class="fa fa-wpforms"></i>
          <span>EOD</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{route('sale.create')}}"><i class="fa fa-circle-o"></i> Add Sale</a></li>
        </ul>
      </li>
      @endhasrole
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

resources/views/pages/partials/success.blade.php
@if (session('message'))
  <div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <p><i class="icon fa fa-check"></i> {{ session('message') }}</p>
  </div>
@endif